spring:
  datasource:
    url: jdbc:mysql://db:3306/cards?useSSL=false
    password: dbcardspassword
    username: dbcards
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: none
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-admin-service:8761/eureka/

swagger:
  api-version: 1.0
  title: Card API
  description: Documentation Card API v${swagger.api-version}

springfox:
  documentation:
    swagger:
      v2:
        path: /cards/v2/api-docs

