spring:
  datasource:
    url: jdbc:mysql://db:3306/users
    password: dbuserspassword
    username: dbusers
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: none
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-admin-service:8761/eureka/